### PR TITLE
bug fix for GPIO port other than 15

### PR DESCRIPTION
**Pull request by cgalpin**

### CODE REVIEW

**Comment by NeonHorizon** [comment]
Thanks!

**Comment by cgalpin** [comment]
No, thank you!

BTW, the files all have dos line endings (CRLF) which is a bit annoying on the pi. I converted them all using 

`perl -pi -e 's/\r\n/\n/g' filename `

in case you want to switch them to unix line endings.

**Comment by NeonHorizon** [comment]
Thats odd, I wonder why the original contributor did that?
I'm like you I always use Unix.

**Comment by NeonHorizon** [comment]
BTW theres a command on Linux dos2unix which converts files, easier to remember than the perl ;)

**Comment by NeonHorizon** [comment]
Being able to remember Perl must be really useful, I can never use it without a cheat sheet :)
The shutdown must be a permissions or path thing I'm guessing?

**Comment by cgalpin** [comment]
I'm the same way with sed and awk so just use perl as soon as things get heavy. It's a bit lazy, but it works for me :)

Yes I agree, but I think both are covered. The cron job runs a root, and the full path of shutdown is bing used. Really odd.

**Pull request merged**
